pipeline {
    agent any

    environment {
        IMAGE_NAME = 'shiva9828/devops-demo'
        IMAGE_TAG = 'latest'
        DOCKERFILE_BASE = 'Dockerfile'
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                url: 'https://github.com/shivashankarbukka402/project2.git'
            }
        }

        stage('Build with Maven') {
            steps {
                script {
                   dir('java-devops-project') {   
                      sh 'mvn clean package'
                      sh 'mvn clean compile'
                   }
                }
            }
        }

        stage('Sonar Code Quality check') {
            steps {
                script {
                    dir('java-devops-project') {
                        withCredentials([string(credentialsId: 'SONAR_TOKEN', variable: 'SONAR_TOKEN')]) {
                            sh """
                                sonar-scanner -X \
                                  -Dsonar.projectKey=java-devops-project \
                                  -Dsonar.sources=. \
                                  -Dsonar.host.url=http://3.111.214.251:9000 \
                                  -Dsonar.login=$SONAR_TOKEN
                            """
                        }
                    }
                }
            }
        }
        stage('Docker Build and Push') {
            steps {
                script { 
                    sh '''
                        ls -lrt
                    '''
                    dir('java-devops-project') {
                        dockerImage = docker.build("${IMAGE_NAME}:${IMAGE_TAG}", "-f ${DOCKERFILE_BASE} .")
                        docker.withRegistry('', "${DOCKER_REGISTRY_CRED_ID}") { 
                            dockerImage.push() 
                        }
                    }
                }
            }
        }
         stage('Trivy Scan') {
            steps {
                sh '''
                    trivy image \
                    --severity HIGH,CRITICAL \
                    --format template \
                    --template '@/home/ubuntu/trivy/trivy_html.tpl' \
                    --output 'trivy_backend.html' ${IMAGE_NAME}:${IMAGE_TAG}
                '''
            }
        }
    }
}
  
